version: '3.8'
services:
  csharp-api:
    build:
      context: ./Csharp.Api
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443      
      - ConnectionStrings__OracleConnection=Data Source=VER_OVERRIDE
