services:
  mottu-csharp-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__OracleConnection=PLEASE_OVERRIDE_IN_LOCAL_SETTINGS

  ef-tools:
    build:
      context: .
      dockerfile: Dockerfile
      target: ef-tools-env
    volumes:
      - .:/app 
    environment:
      - ConnectionStrings__OracleConnection=PLEASE_OVERRIDE_IN_LOCAL_SETTINGS_FOR_EF_TOOLS
      - ASPNETCORE_ENVIRONMENT=Development
